version: '3.8'

services:
  clio:
      container_name: ${PROJECT_NAME}_clio
      build:
        dockerfile: Dockerfile
        context: "./docker/clio"
      restart: always
      volumes:
        - ./docker/clio/config:/config

  xrpl:
      container_name: ${PROJECT_NAME}_xrpl
      build:
        dockerfile: Dockerfile
        context: "./docker/xrpl"
      restart: always
      ports:
        - 5005:5005
        - 6005:6005
        - 51234:51234
        - 51235:51235

  cassandra:
      container_name: ${PROJECT_NAME}_cassandra
      build:
        dockerfile: Dockerfile
        context: "./docker/cassandra"
      restart: always
      volumes:
        - ./docker/clio/config:/config

  scylla:
      container_name: ${PROJECT_NAME}_scylla
      build:
        dockerfile: Dockerfile
        context: "./docker/scylla"
      restart: always
      volumes:
        - ./docker/clio/config:/config


