version: "3.8"

services:
  scylla-manager:
      image: scylladb/scylla-manager
      networks:
        scylla:
      depends_on:
        - scylla-manager-db

  scylla-manager-db:
      image: scylladb/scylla
      volumes:
        - ./scylla_manager_db_data:/var/lib/scylla
      networks:
        scylla:
      command: --smp 1 --memory 100M

  scylla:
      build:
        context: .
      image: scylladb/scylla-with-agent
      volumes:
        - ./scylla_data:/var/lib/scylla
      networks:
        scylla:
      command: --smp 1 --memory 1G

  minio:
      image: minio/minio
      volumes:
        - ./minio:/data
      networks:
        scylla:
      ports:
        - "9001:9000"
      environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: minio123
      command: server /data
        
networks:
      scylla:
        driver: bridge
        ipam:
          driver: default